# Generated by Django 4.2.4 on 2023-08-27 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passanger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passanger',
            new_name='Passangers',
        ),
    ]
